version: "3"
services:
  httpd:
    build:
      context: "${LOCAL_HOST_PATH}/httpd"
      dockerfile: Dockerfile
      args:
        - DOCUMENT_ROOT=/home/${XSERVER_ID}/${XSERVER_DOMAIN}/public_html/${XSERVER_SUBDOMAIN}
        - USERNAME=${USERNAME}
    container_name: "${PROJECT_NAME}_httpd"
    env_file: .env
    environment:
      TZ: Asia/Tokyo
    ports:
      - "80:80"
      - "8080:8080"
    tty: true
    user: "${USERNAME}:${USERNAME}"
    volumes:
      - ${LOCAL_HOST_PATH}:/home/${XSERVER_ID}/${XSERVER_DOMAIN}/repos/${XSERVER_SUBDOMAIN}
      - /home/${XSERVER_ID}/${XSERVER_DOMAIN}/public_html
      - /home/${XSERVER_ID}/${XSERVER_DOMAIN}/repos/${XSERVER_SUBDOMAIN}/node_modules
      - /home/${XSERVER_ID}/${XSERVER_DOMAIN}/repos/${XSERVER_SUBDOMAIN}/vendor
    working_dir: "/home/${XSERVER_ID}/${XSERVER_DOMAIN}/repos/${XSERVER_SUBDOMAIN}"
  mariadb:
    image: mariadb:10.5
    container_name: "${PROJECT_NAME}_mariadb"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    container_name: "${PROJECT_NAME}_phpmyadmin"
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8888:80"
